Update _index.md
open-cluster-management-io/open-cluster-management-io.github.io pull request #102
Opened 2021-06-28 09:18 UTC by xuezhaojun

Signed-off-by: xuezhaojun <zxue@redhat.com>

2021-06-28 09:18 UTC, xuezhaojun commented
/assign @qiujian16

2021-06-29 06:25 UTC, qiujian16 commented on content/getting-started/quick-start/_index.md
> +## Create hub cluster and managed cluster by [kind](https://kind.sigs.k8s.io/)
Two clusters are needed before the installation, one as hub cluster ... 
To prepare two clusters using kind, run the following command.



## Install via clusteradm
### download clusteradm
### install hub
### install spoke

## install via operatorhub

2021-06-29 07:23 UTC, qiujian16 commented on content/getting-started/quick-start/_index.md
> -{{< toc >}}
can't you use {{< toc >}} here?

2021-06-29 07:24 UTC, xuezhaojun commented on content/getting-started/quick-start/_index.md
> +## Create hub cluster and managed cluster by [kind](https://kind.sigs.k8s.io/)
Done.

2021-06-29 07:24 UTC, qiujian16 commented on content/getting-started/quick-start/_index.md
> +    ```
Shell?

2021-06-29 07:25 UTC, qiujian16 commented on content/getting-started/quick-start/_index.md
> +    ```
Shell?

2021-06-29 07:26 UTC, qiujian16 commented on content/getting-started/quick-start/_index.md
> +Before installation, we need to create two clusters. One used as hub cluster and another as managed cluster.
Before installation, prepare a multicluster environment with at least two clusters. One used as hub cluster and another as a managed cluster.

2021-06-29 07:32 UTC, xuezhaojun commented
Please wait a moment for update

2021-06-29 07:37 UTC, xuezhaojun commented
Updated the latest edition.

2021-06-29 07:54 UTC, qiujian16 commented
/approve

@mikeshng you  want to take a look?

2021-06-29 13:58 UTC, mikeshng requested changes
These are some really good changes but please use `make server` and browse to the page to make sure everything looks ok. IDE's .md preview will give you a good idea of how the page will look like but there are some differences compare to actual hugo deployment.

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +You can create these two clusters using [kind](https://kind.sigs.k8s.io/). Run the following commands:
minor nit: remove the trailing `/` after `.io`.

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +kind create cluster --name <your managed cluster name> # kind create cluster --name spoke
Instead of `spoke` use `cluster1` which seems to be default sample managed cluster name 
https://github.com/open-cluster-management-io/registration-operator/blob/main/deploy/klusterlet/config/samples/operator_open-cluster-management_klusterlets.cr.yaml#L8
and many more references of `cluster1` on the website: https://open-cluster-management.io/getting-started/core/register-cluster/

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +### Install and create a [cluster manager](https://operatorhub.io/operator/cluster-manager) on your _hub_ cluster
```suggestion
### Deploy a `cluster manager` on your _hub_ cluster
```
Lets not link out to operatorhub here because it contains install instructions and might be confusing for reader.

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +   Copy the generated command and modify the `<managed_cluster_name>` to your managed cluster name. E.g. `cluster0`.
use `cluster1`

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +    please log on spoke and run:
Replace `please log on spoke and run:` with `...`

We need to improve the UX of clusteradm. This clusteradm output mention `spoke` but generally we use the term `managed` cluster. For now I think we should just not show this sentence and only show the `clusteradm join....` part.

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +    ```Shell
add a new line before ```Shell

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +    ```Shell
add a new line before ```Shell

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +2. Bootstrap the Open Cluster Management control plane:
add a new line before `2. ...`

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +   Then you will get a result with a generated `join` command:
add a new line before `Then...`

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +    ```Shell
add a new line before ```Shell

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +   Copy the generated command and modify the `<managed_cluster_name>` to your managed cluster name. E.g. `cluster0`.
add a new line before `Copy...`

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +### Install and create a [klusterlet agent](https://operatorhub.io/operator/klusterlet) on your _manage_ cluster
Add some new lines similar to the previous recommendations.
Make sure you run `make server` and browse to this page to double check the consistency of the page after your changes.

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +   Copy the generated command and modify the `<managed_cluster_name>` to your managed cluster name. E.g. `cluster0`.
instead of `modify` maybe its better to use the word `replace`

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +    kubectl config use-context <managed cluster context> # kubectl config use-context kind-spoke
`kind-cluster1`

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +2. Run the generated `join` command to join the hub cluster:
```suggestion
2. Run the previously copied `join` command to join the hub cluster:
```

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +    clusteradm accept --clusters <managed_cluster_name> # clusteradm accept --clusters cluster0
use `cluster1`

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +2. Accept request:
We might want to add a step before `Accept request` to talk about when user can actually accept the request and expect it to work.
I think it takes at least a few minutes before the CSR and the managedcluster CR is generated on the hub.
Maybe we have to do some get in combination with watch flag. @qiujian16 what do you think?

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +### Install and create a [klusterlet agent](https://operatorhub.io/operator/klusterlet) on your _manage_ cluster
```suggestion
### Deploy a `klusterlet` agent on your _manage_ cluster
```
lets not link out to operatorhub here similar to cluster manage above.

2021-06-29 13:58 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +    cluster0   true           https://127.0.0.1:41478   True     True        5m23s
`cluster1` instead of `cluster0`

2021-06-29 14:00 UTC, mikeshng commented
![image](https://user-images.githubusercontent.com/58747157/123810790-af38fc80-d8c0-11eb-916e-c0989ca5b629.png)

I feel like we use too much of the word `Install`

Lets do something like:
```
Bootstrap via Clusteradm CLI tool
    Install Clusteradm CLI tool
    Deploy a cluster manager on your hub cluster
    Deploy a klusterlet agent on your manage cluster
    Accept join request and verify
Bootstrap via Operatorhub.io
```

2021-06-29 17:17 UTC, xuezhaojun commented
@mikeshng  Thanks for advise and using "make server" to check in browser helps a lot!

A little more change is I modified:

```mk
### Deploy a `cluster` manager on your _hub_ cluster
```

to 

```mk
### Deploy a cluster manager on your hub cluster
```

since hugo can't show special format in heading, it will delete whithspaces around words with special format.

![image](https://user-images.githubusercontent.com/11444421/123840400-db945d80-d940-11eb-9a95-221b81b6a916.png)

2021-06-29 18:51 UTC, mikeshng reviewed
I think the changes are good to go after these small nits. @qiujian16 feel free to tag lgtm when you are ready.

2021-06-29 18:51 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +### Accept `join` request and verify
```suggestion
### Accept the join request on your hub cluster and verify
```
Let's remove these formatting in headers because they don't display nicely.

2021-06-29 18:51 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +### Deploy a `klusterlet` agent on your _manage_ cluster
```suggestion
### Deploy a klusterlet agent on your manage cluster
```
Let's remove these formatting in headers because they don't display nicely.

2021-06-29 18:51 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +### Deploy a `cluster manager` on your _hub_ cluster
```suggestion
### Deploy a cluster manager on your hub cluster
```
Let's remove these formatting in headers because they don't display nicely.

2021-06-30 03:28 UTC, qiujian16 commented
/approve
/lgtm

2021-06-30 03:28 UTC, merged