Update GRC
open-cluster-management-io/open-cluster-management-io.github.io pull request #108
Opened 2021-07-02 05:05 UTC by dhaiducek

I started out following the commands given and using the raw content GitHub links, but now I'm wondering if it'd be better to use the make targets inside each repo... (Since that's what other instructions do and it'd be a bit cleaner.) The downside is that it'd require cloning 5 different repos, and I wasn't sure whether the priority was to get things running (without clogging up the filesystem). I think I've talked myself into reworking it again to use `git clone`, but I'd appreciate feedback also (since it's late and I'm not thinking straight)!

2021-07-02 05:05 UTC, dhaiducek commented
/assign @mikeshng 
/assign @JustinKuli

2021-07-02 13:46 UTC, JustinKuli reviewed
I just have some small thoughts/suggestions.

The GIT_PATH and COMPONENT vars make the kubectl apply commands more reasonable. I think it is better than asking the user to clone all of the repos locally, and I think it's the best we can do.

2021-07-02 13:46 UTC, JustinKuli commented on content/getting-started/integration/policy-controllers.md
> +   kubectl set env deployment/${COMPONENT} -n ${MANAGED_NAMESPACE} --containers=${COMPONENT} WATCH_NAMESPACE=${MANAGED_CLUSTER_NAME}
I like the definition and use of GIT_PATH here

2021-07-02 13:46 UTC, JustinKuli commented on content/getting-started/integration/policy-framework.md
> +After the cluster manager and klusterlet are installed and application management is installed, you can install the policy framework components to the hub and the managed clusters.
```suggestion
After the cluster manager, klusterlet, and application management components are installed, you can install the policy framework components to the hub and the managed clusters.
```
Unless there was a good reason to avoid grouping all three together

2021-07-02 13:46 UTC, JustinKuli commented on content/getting-started/integration/policy-framework.md
> +   done
I'm not sure if I like the for loop. It does make it more clear that all of these are installed the same way... but it feels weird to not be able to run each line of the installation individually. I can really see it going either way.

If it did split into separate commands, I think expanding the COMPONENT would be nice (for example `export COMPONENT="governance-policy-spec-sync"`).

2021-07-02 14:12 UTC, dhaiducek commented on content/getting-started/integration/policy-framework.md
> +   done
That's true--for something users are copying/pasting, perhaps this should even be split into separate steps to make it clearer what's going on. A `for` loop might be getting too script-y and less command-y.

2021-07-02 14:13 UTC, dhaiducek commented on content/getting-started/integration/policy-framework.md
> +After the cluster manager and klusterlet are installed and application management is installed, you can install the policy framework components to the hub and the managed clusters.
I was thinking of keeping components grouped together, but I like yours better (and the Oxford comma to boot!)

2021-07-03 01:34 UTC, mikeshng requested changes
Thanks @dhaiducek ! Just a small fix needed and 2 minor nits

@qiujian16 I've tried these instructions and they work well. Could you please take a quick look and approve lgtm? Thanks.

2021-07-03 01:34 UTC, mikeshng commented on content/getting-started/integration/policy-framework.md
> +   done
Remove `done`.

2021-07-03 01:34 UTC, mikeshng commented on content/getting-started/integration/policy-controllers.md
>  weight: 2
```suggestion
weight: 11
```
lets put the policy after app because it has a dependency on app.

2021-07-03 01:34 UTC, mikeshng commented on content/getting-started/integration/policy-framework.md
>  weight: 1
```suggestion
weight: 10
```
lets put policy after apps since it has a dependency on app installed first.

2021-07-03 01:42 UTC, qiujian16 commented
/approve
/lgtm

I am concerned about taking application management as a pre-requirement. Would you create an issue in community repo to make it install independently?

2021-07-03 01:43 UTC, merged