set common env and reduce the kube context switch.
open-cluster-management-io/open-cluster-management-io.github.io pull request #118
Opened 2021-07-07 11:11 UTC by morvencao

This PR tries to enhance the document:
- set some common environment variables at the beginning of the whole guideline.
- try to reduce the kube context switch, for example, `clusteradm` support `--context` flag, so we can use that to quickly refer to the expected kube context.
- reduce duplicated environment variable definition, for example, `MANAGED_CLUSTER_NAME` can be exported after the cluster is created by the `kind` command and then it will be reused throughout the guideline.
- fix typo.

Signed-off-by: morvencao <lcao@redhat.com>

2021-07-07 15:01 UTC, mikeshng commented
Thank you for the PR. I will need to at least run it once myself to verify the steps.

2021-07-22 09:00 UTC, morvencao commented
@mikeshng Another look? I rebased code changes.

2021-07-22 13:21 UTC, mikeshng commented
@morvencao sorry for the delay. I will get to this today.

2021-07-22 17:00 UTC, mikeshng requested changes
I am ok with all the changes but have some concerns for the `quick-start` ones.

@qiujian16 @itdove could you please share your thoughts? Should we update `clusteradm` outputs with the `--context` flag before making the suggested change here?

2021-07-23 01:43 UTC, morvencao commented on content/getting-started/quick-start/_index.md
> +   clusteradm join --hub-token <token_data> --hub-apiserver https://126.0.0.1:39242 --cluster-name ${MANAGED_CLUSTER_NAME} --context ${CTX_MANAGED_CLUSTER}
Make sense, I updated the command to put the `--context` flag near the beginning the `clusteradm join` command.

Also if you take a look at the instruction before the command, I explicitly add the notice to let user append the `--context` flag after copy the command.

`Run the previously copied 'join' command **by appending the context of your managed cluster to join the hub cluster:**'

2021-07-23 02:08 UTC, mikeshng commented
/approve

will lgtm in today if I don't hear some feedback from Dominique or Qiu Jian

2021-07-23 12:15 UTC, qiujian16 commented
> I am ok with all the changes but have some concerns for the `quick-start` ones.
> 
> @qiujian16 @itdove could you please share your thoughts? Should we update `clusteradm` outputs with the `--context` flag before making the suggested change here?

--context could be a global flag similar as kubectl so you could have clusteradm options to know all the global flags.

2021-07-23 12:32 UTC, itdove commented on content/getting-started/quick-start/_index.md
> +   clusteradm join --hub-token <token_data> --hub-apiserver https://126.0.0.1:39242 --cluster-name ${MANAGED_CLUSTER_NAME} --context ${CTX_MANAGED_CLUSTER}
@morvencao, where is your change in the clusteradm repo join command, I don't find it?
The --context is part of the standard kubectl genericoptions and they are in alphabetic order, I would not change that order.

2021-07-23 13:35 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +   clusteradm join --hub-token <token_data> --hub-apiserver https://126.0.0.1:39242 --cluster-name ${MANAGED_CLUSTER_NAME} --context ${CTX_MANAGED_CLUSTER}
I thought we have the `--context` flag for `clusteradm` already.
```
$ clusteradm --help | grep context
      --context string                   The name of the kubeconfig context to use
```

I was referring to the STDOUT that user have to copy and paste after running `clusteradm init` not having the `--context` yet.
```
$ clusteradm init
The multicluster hub control plane has been initialized successfully!

You can now register cluster(s) to the hub control plane. Log onto those cluster(s) and run the following command:

    clusteradm join --hub-token ....
```

2021-07-23 14:10 UTC, mikeshng commented
/lgtm 

After verifying that `clusteradm join --context ${CTX_MANAGED_CLUSTER} --hub-token ...` works fine.

2021-07-23 14:11 UTC, merged