Doc: Adding cluster-proxy doc
open-cluster-management-io/open-cluster-management-io.github.io pull request #159
Opened 2021-11-23 11:58 UTC by yue9944882

> Signed-off-by: yue9944882 <291271447@qq.com>

2021-11-23 14:41 UTC, mikeshng requested changes
This is a really well written article. Thank you Min. I just have some minor nits. I will defer to Qiu Jian for another look. 
I did notice you only added the `en` file. Maybe just copy and paste it to the `zh` folder as well because that's how other not yet translated pages are currently.

2021-11-23 14:41 UTC, mikeshng commented on content/en/getting-started/integration/cluster-proxy.md
> +Cluster proxy is an OCM addon providing L4 network connectivity from hub
```suggestion
[Cluster proxy](https://github.com/open-cluster-management-io/cluster-proxy) is an OCM addon providing L4 network connectivity from hub 
```

2021-11-23 14:41 UTC, mikeshng commented on content/en/getting-started/integration/cluster-proxy.md
> +managed clusters which will need the "hub -> kluster" connectivity on
```suggestion
managed clusters which will need the "hub -> klusterlet" connectivity on 
```
Earlier there was a usage of `"klusterlet -> hub"`so maybe using `klusterlet` here is better.

2021-11-23 14:41 UTC, mikeshng commented on content/en/getting-started/integration/cluster-proxy.md
> +$ helm repo add ocm https://open-cluster-management.oss-us-west-1.aliyuncs.com
Side discussion: maybe we should create a helm chart repo for OCM and use https://github.com/helm/chart-releaser-action to manage it. That way the helm repo will be under ocm io github domain.

2021-11-23 15:30 UTC, yue9944882 commented on content/en/getting-started/integration/cluster-proxy.md
> +Cluster proxy is an OCM addon providing L4 network connectivity from hub
updated

2021-11-23 15:31 UTC, yue9944882 commented on content/en/getting-started/integration/cluster-proxy.md
> +managed clusters which will need the "hub -> kluster" connectivity on
rephrased to klusterlet

2021-11-23 15:35 UTC, yue9944882 commented on content/en/getting-started/integration/cluster-proxy.md
> +$ helm repo add ocm https://open-cluster-management.oss-us-west-1.aliyuncs.com
i think so. we should probably start by creating a repo under the organization (e.g. named `chart`), is it? and i remember the azure folks are interested in hosting a OSS bucket for OCM charts. am fine w/ either ways tho.

2021-11-23 17:06 UTC, ryanzhang-oss commented on content/en/getting-started/integration/cluster-proxy.md
> +$ helm repo add ocm https://open-cluster-management.oss-us-west-1.aliyuncs.com
Yes, we can definitely host the OCM helm charts. The most straightforward way is to just put it on a blob in Azure. However, I wonder if it's okay to expose the azure related URL in the helm repo info?

2021-11-24 06:03 UTC, yue9944882 commented on content/en/getting-started/integration/cluster-proxy.md
> +$ helm repo add ocm https://open-cluster-management.oss-us-west-1.aliyuncs.com
@ryanzhang-oss not at all. remember the official kubernetes images are hosted on `gcr.io`, it's fine to drop the release builds on any vendor as long as we can govern the release process.

2021-11-24 11:37 UTC, qiujian16 reviewed
/approve
/lgtm

2021-11-24 11:38 UTC, merged