Doc: Convinient way to install clusteradm
open-cluster-management-io/open-cluster-management-io.github.io pull request #170
Opened 2021-12-08 14:06 UTC by yue9944882

> Signed-off-by: yue9944882 <291271447@qq.com>

2021-12-08 14:06 UTC, yue9944882 commented
/cc @qiujian16

2021-12-08 14:44 UTC, mikeshng requested changes
Minor nits. Thanks for updating the doc.

2021-12-08 14:44 UTC, mikeshng commented on content/en/getting-started/quick-start/_index.md
> +It's recommended to install with the following command if you have a golang
```suggestion
It's recommended to install with the following command if you have a `golang` 
```

2021-12-08 14:44 UTC, mikeshng commented on content/en/getting-started/quick-start/_index.md
> +Otherwise if you don't have golang library in the local environment, you can also
```suggestion
Otherwise if you don't have a `golang` environment, you can also 
```
We should either use `golang` environment or `golang` library in the local environment but not both.

2021-12-09 03:20 UTC, yue9944882 commented on content/en/getting-started/quick-start/_index.md
> +Otherwise if you don't have golang library in the local environment, you can also
fixed

2021-12-09 03:20 UTC, yue9944882 commented on content/en/getting-started/quick-start/_index.md
> +It's recommended to install with the following command if you have a golang
quoted

2021-12-09 03:24 UTC, qiujian16 commented
/approve
/lgtm

2021-12-09 03:26 UTC, merged