Doc: Exercise proxy framework
open-cluster-management-io/open-cluster-management-io.github.io pull request #177
Opened 2021-12-15 09:44 UTC by yue9944882

> Signed-off-by: yue9944882 <291271447@qq.com>

2021-12-15 15:16 UTC, qiujian16 reviewed
/approve
/assign @mikeshng

2021-12-15 17:37 UTC, mikeshng requested changes
Thank for the detailed documentation. Just some minor nits/suggestions

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +title: Pushing kube API requests to the managed clusters
```suggestion
title: Pushing Kubernetes API requests to the managed clusters
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +to "push" kubernetes API requests to the managed clusters with everything
```suggestion
to "push" Kubernetes API requests to the managed clusters.
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +automated by a few OCM addons. The amazing part of "pushing" requests in OCM
```suggestion
The benefit of using this method for "pushing" requests
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +managed clusters or provide any client credentials as preparation. Literally
```suggestion
managed clusters or provide any client credentials as preparation.
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +everything needed is to enable/install the following OCM addons:
```suggestion
We just need to enable/install the following OCM addons:
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +is that we don't need either to explicitly configure any API endpoint for the
```suggestion
is that we don't need to explicitly configure any API endpoint for the 
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +  and projecting the tokens back to the hub cluster so that the kube API clients
```suggestion
  and projecting the tokens back to the hub cluster so that the Kubernetes API clients
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +  from the hub make the requests properly authenticated.
```suggestion
  from the hub can make authenticated requests.
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +  gracefully access the managed clusters by standard kube API calls (including
```suggestion
  gracefully access the managed clusters by standard Kubernetes API calls (including
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +The commands above are basically installing the addon manager into the hub
```suggestion
The commands above installs the addon manager into the hub 
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +cluster, and the manager will be automatically creating `ManagedClusterAddon`
```suggestion
cluster, and the manager will create the `ManagedClusterAddon` automatically
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +cluster. In order to check out their status, run:
```suggestion
cluster. In order to check their status, run:
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +Furthermore, after the addons are all set, the hub admin will be able to see a
```suggestion
Furthermore, after the addons are all deployed successfully, the hub admin will be able to see a
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +And interestingly you can also easily convert the kubeconfig of the hub cluster
```suggestion
Another nice feature is that you can also easily convert the kubeconfig of the hub cluster
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +That is because we haven't set up proper RBAC permissions for the "egress"
```suggestion
That is because we haven't set up proper RBAC permissions for the `egress`
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +will be free to operate the managed cluster from the hub without asking for
```suggestion
will be able to freely operate the managed cluster from the hub without asking for
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +account is also periodically rotated by the addons so there's no worry in
```suggestion
account is also periodically rotated by the addons so there's no need to worry about
```

2021-12-15 17:37 UTC, mikeshng commented on content/en/scenarios/pushing-kube-api-requests.md
> +which provides you plenty much of utilities for further customization.
```suggestion
which provides you utilities for further customization.
```

2021-12-15 17:37 UTC, mikeshng commented on i18n/en.toml
> +other = "Pushing Kube API Requests to the Managed Clusters"
```suggestion
other = "Pushing Kubernetes API Requests to the Managed Clusters"
```

2021-12-15 17:37 UTC, mikeshng commented on content/zh/scenarios/pushing-kube-api-requests.md
> +---
Same edit as the English files above.

2021-12-15 17:37 UTC, mikeshng commented on i18n/zh.toml
> +other = "向托管集群推送Kube API请求"
```suggestion
other = "向托管集群推送Kubernetes API请求"
```

2021-12-16 06:14 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +title: Pushing kube API requests to the managed clusters
updated

2021-12-16 06:15 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +to "push" kubernetes API requests to the managed clusters with everything
updated

2021-12-16 06:15 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +automated by a few OCM addons. The amazing part of "pushing" requests in OCM
updated

2021-12-16 06:15 UTC, yue9944882 commented on i18n/en.toml
> +other = "Pushing Kube API Requests to the Managed Clusters"
updated

2021-12-16 06:15 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +which provides you plenty much of utilities for further customization.
updated

2021-12-16 06:16 UTC, yue9944882 commented on content/zh/scenarios/pushing-kube-api-requests.md
> +---
yep

2021-12-16 06:16 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +account is also periodically rotated by the addons so there's no worry in
updated

2021-12-16 06:16 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +will be free to operate the managed cluster from the hub without asking for
updated

2021-12-16 06:16 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +That is because we haven't set up proper RBAC permissions for the "egress"
changed quote type

2021-12-16 06:16 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +And interestingly you can also easily convert the kubeconfig of the hub cluster
updated

2021-12-16 06:17 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +Furthermore, after the addons are all set, the hub admin will be able to see a
updated

2021-12-16 06:17 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +cluster. In order to check out their status, run:
updated

2021-12-16 06:17 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +cluster, and the manager will be automatically creating `ManagedClusterAddon`
updated

2021-12-16 06:17 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +The commands above are basically installing the addon manager into the hub
updated

2021-12-16 06:17 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +  from the hub make the requests properly authenticated.
updated

2021-12-16 06:17 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +  gracefully access the managed clusters by standard kube API calls (including
updated

2021-12-16 06:17 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +  and projecting the tokens back to the hub cluster so that the kube API clients
updated

2021-12-16 06:17 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +everything needed is to enable/install the following OCM addons:
updated

2021-12-16 06:18 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +managed clusters or provide any client credentials as preparation. Literally
updated

2021-12-16 06:18 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +is that we don't need either to explicitly configure any API endpoint for the
updated

2021-12-16 06:18 UTC, yue9944882 commented on content/en/scenarios/pushing-kube-api-requests.md
> +to "push" kubernetes API requests to the managed clusters with everything
updated

2021-12-16 06:26 UTC, qiujian16 commented
/approve
/lgtm

2021-12-16 06:27 UTC, merged