Add 0.6 release announce
open-cluster-management-io/open-cluster-management-io.github.io pull request #199
Opened 2022-01-21 15:41 UTC by qiujian16

Signed-off-by: Jian Qiu <jqiu@redhat.com>

2022-01-21 15:42 UTC, qiujian16 commented
/hold

still waiting for more input.

2022-01-21 15:56 UTC, mikeshng requested changes
Just some minor nits. Thank you for the release summary.

2022-01-21 15:56 UTC, mikeshng commented on content/en/community/releases.md
> +- [Syn status of applied resources in ManifestWork](https://github.com/open-cluster-management-io/enhancements/tree/main/enhancements/sig-architecture/29-manifestwork-status-feedback)
```suggestion
- [Sync status of applied resources in ManifestWork](https://github.com/open-cluster-management-io/enhancements/tree/main/enhancements/sig-architecture/29-manifestwork-status-feedback)
```

2022-01-21 15:56 UTC, mikeshng commented on content/en/community/releases.md
> +We also add many new functions in [clusteradm](https://github.com/open-cluster-management-io/clusteradm) and enhacements on documentation in the website.
```suggestion
We also added many new functions in [clusteradm](https://github.com/open-cluster-management-io/clusteradm) and enhancements on documentation in the website.
```

2022-01-21 15:56 UTC, mikeshng commented on content/en/community/releases.md
> +- cluster-proxy v0.1.3 [changelog]
```suggestion
- cluster-proxy v0.1.3 [repo](https://github.com/open-cluster-management-io/cluster-proxy)
```

2022-01-21 16:04 UTC, mikeshng commented on content/en/community/releases.md
> +
```suggestion
- [Placement API support for multicloud-operators-subscription](https://github.com/open-cluster-management-io/multicloud-operators-subscription/pull/55)

```

2022-01-24 01:45 UTC, zhujian7 commented on content/en/community/releases.md
> +- registration-operator v0.6.0 [changelog](https://github.com/open-cluster-management-io/registration-operator/blob/v0.5.0/CHANGELOG/CHANGELOG-v0.6.md)
The link is unavailable. should be `https://github.com/open-cluster-management-io/registration-operator/blob/v0.6.0/CHANGELOG/CHANGELOG-v0.6.md`?

2022-01-24 01:54 UTC, qiujian16 commented on content/en/community/releases.md
> +- registration-operator v0.6.0 [changelog](https://github.com/open-cluster-management-io/registration-operator/blob/v0.5.0/CHANGELOG/CHANGELOG-v0.6.md)
thanks for reminding. fixed

2022-01-24 05:27 UTC, yue9944882 reviewed
LGTM

2022-01-24 14:23 UTC, mikeshng approved these changes
/lgtm

2022-01-24 19:33 UTC, juliana-hsu commented on content/en/community/releases.md
> +Open Cluster Management team is proud to announce the release of OCM v0.6.0! We made many enhancements on core components and introduced some new addons.
The Open Cluster Management team ...

2022-01-24 19:37 UTC, juliana-hsu commented on content/en/community/releases.md
> +We also added many new functions in [clusteradm](https://github.com/open-cluster-management-io/clusteradm) and enhancements on documentation in the website.
... and enhanced the website documentation.

2022-01-24 19:38 UTC, juliana-hsu commented on content/en/community/releases.md
> +To see details of the changelogs in this release:
See details in the release changelogs:

2022-01-24 22:17 UTC, mdelder commented
So many great enhancements! 

Are there docs for the new features beyond the repo READMEs (for the cluster proxy and `ManagedServiceAccount`)? Would it be helpful to link to those docs/getting started pages if they exist?

2022-01-25 05:18 UTC, yue9944882 commented
@mdelder the doc for cluster-proxy and managed-serviceaccount is already available at:

https://open-cluster-management.io/getting-started/integration/cluster-proxy/
https://open-cluster-management.io/getting-started/integration/managed-serviceaccount/

additionally there's a tutorial for plumbing up these addons together:

https://open-cluster-management.io/scenarios/pushing-kube-api-requests/

2022-01-25 07:37 UTC, qiujian16 commented
> So many great enhancements!
> 
> Are there docs for the new features beyond the repo READMEs (for the cluster proxy and `ManagedServiceAccount`)? Would it be helpful to link to those docs/getting started pages if they exist?

Thanks, added some overview with each key feature and the links to relating docs/examples.

2022-01-26 03:09 UTC, mikeshng commented
/lgtm

2022-01-26 06:17 UTC, qiujian16 commented
/unhod

2022-01-26 06:17 UTC, qiujian16 commented
/unhold

2022-01-26 06:18 UTC, merged