update policy doc to make it easy for read
open-cluster-management-io/open-cluster-management-io.github.io pull request #248
Opened 2022-04-15 08:24 UTC by jichenjc

Signed-off-by: jichenjc <jichenjc@cn.ibm.com>

2022-04-15 17:52 UTC, mikeshng commented
These changes look good to me. I am going to let the policy team to take another quick look.

/approve

/assign mprahl

/assign dhaiducek

2022-05-02 21:56 UTC, dhaiducek requested changes
Thanks for these updates! These docs were definitely written assuming the env had been stored from deploying the core components. (Deploying policy will also become easier once our addon controller is implemented and added to `clusteradm`.)

I've added some feedback.

2022-05-02 21:56 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +   # Create the namespace for the synchronization components, optional if `clusteradm` is used as it's already created
Is this always true? Unless I'm mistaken, I think this would only be true if the Application components were added prior to this. (We're currently working on adding the addon to `clusteradm` for policy.) Assuming this is correct, I think I'd prefer to leave this off.

2022-05-02 21:56 UTC, dhaiducek commented on content/zh/getting-started/integration/policy-framework.md
> +   kubectl create ns ${MANAGED_CLUSTER_NAME}
Great catch--thanks for updating this!

2022-05-02 21:56 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +# set the operated namespace
```suggestion
# Set the deployment namespace
```

2022-05-02 21:56 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +# Set hub cluster name
```suggestion
# Set the hub cluster name
```

2022-05-02 21:56 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +# set hub kubeconfig file
```suggestion
# Set the hub kubeconfig file
```

2022-05-06 07:21 UTC, jichenjc commented on content/en/getting-started/integration/policy-framework.md
> +   # Create the namespace for the synchronization components, optional if `clusteradm` is used as it's already created
ok, from my test it's not needed but for safe, I can remove above sentence

2022-05-06 16:03 UTC, dhaiducek commented
Thanks for these updates! I'm assuming we need to copy the changes over to the `zn/` files? Other than that, I think this is good to be merged.

2022-05-10 17:27 UTC, dhaiducek approved these changes

2022-05-10 17:32 UTC, merged