WIP - Add English security reporting page
open-cluster-management-io/open-cluster-management-io.github.io pull request #253
Opened 2022-04-29 20:50 UTC by mikeshng

Signed-off-by: Mike Ng <ming@redhat.com>

2022-04-29 20:52 UTC, mikeshng commented
Hi @pshickeydev whenever you have some cycles could you take a look at this PR and see how to fully describe our security reporting process for the OCM community? Thanks.

2023-02-03 01:17 UTC, mikeshng commented
@pshickeydev could you please take a look at this again? I will also try to update some of the content based on your previous emails.

2025-02-27 15:21 UTC, mikeshng commented
@zhujian7 should we just merge this one first if you think it looks ok?

2025-02-27 15:32 UTC, dhaiducek requested changes
Thanks @mikeshng! Please also re-wrap this file to match the line breaks in other files.

2025-02-27 15:32 UTC, dhaiducek commented on content/en/docs/security/_index.md
> +https://github.com/kubernetes/committee-security-response/blob/main/security-release-process.md
Turn this into a more friendly link, like:
```suggestion
Refer to the Kubernetes [Security Release Process](https://github.com/kubernetes/committee-security-response/blob/main/security-release-process.md) for details on the security disclosures and response policy.
```

2025-02-27 15:32 UTC, dhaiducek commented on content/en/docs/security/_index.md
> +Any vulnerability information shared with OCM project owners stays within OCM community and will not be disseminated to other projects unless it is necessary to get the issue fixed.
```suggestion
Any vulnerability information shared with OCM project owners stays within the OCM community and will not be disseminated to other projects unless it is necessary to get the issue fixed.
```

2025-02-27 15:32 UTC, dhaiducek commented on content/en/docs/security/_index.md
> +The OCM community security reporting process is inspired by the [Kubernetes security reporting process](https://kubernetes.io/docs/reference/issues-security/security/).
I personally don't think where our inspiration comes from is relevant if it's inspiration and not the actual process?

2025-02-28 02:07 UTC, mikeshng commented on content/en/docs/security/_index.md
> +https://github.com/kubernetes/committee-security-response/blob/main/security-release-process.md
Done as suggested. Thanks.

2025-02-28 02:07 UTC, mikeshng commented on content/en/docs/security/_index.md
> +Any vulnerability information shared with OCM project owners stays within OCM community and will not be disseminated to other projects unless it is necessary to get the issue fixed.
Done as suggested. Thanks.

2025-02-28 02:07 UTC, mikeshng commented on content/en/docs/security/_index.md
> +The OCM community security reporting process is inspired by the [Kubernetes security reporting process](https://kubernetes.io/docs/reference/issues-security/security/).
You are right. We might refine the process in the future but I think this is a good start.

2025-02-28 02:59 UTC, zhujian7 commented
> @zhujian7 should we just merge this one first if you think it looks ok?

Absolutely. thanks @mikeshng 
/lgtm
/hold for @qiujian16 @dhaiducek to take a final review.

2025-02-28 14:17 UTC, dhaiducek commented on content/en/docs/security/_index.md
> +If you know of a security issue with OCM, please report it to `OCM-security@googlegroups.com`. The OCM project owners receive security disclosures by default. They may share disclosures with others a
This is still in backticks--is that expected?

2025-02-28 14:20 UTC, dhaiducek commented on content/en/docs/security/_index.md
> +If you know of a security issue with OCM, please report it to `OCM-security@googlegroups.com`. The OCM project owners receive security disclosures by default. They may share disclosures with others a
Actually, I did a "quote reply" on your e-mail from the PR description and got back:
```
[OCM-security@googlegroups.com](mailto:OCM-security@googlegroups.com)
```
So assuming the parsers in the website are similar, that ought to do it?

2025-02-28 19:45 UTC, mikeshng commented on content/en/docs/security/_index.md
> +If you know of a security issue with OCM, please report it to `OCM-security@googlegroups.com`. The OCM project owners receive security disclosures by default. They may share disclosures with others a
Great suggestion! Done as suggested. Thanks.

2025-02-28 19:48 UTC, dhaiducek approved these changes
LGTM! Thanks!

2025-03-01 01:46 UTC, mikeshng commented
/unhold

2025-03-01 01:50 UTC, merged