Add some documentation around templates in config policies
open-cluster-management-io/open-cluster-management-io.github.io pull request #261
Opened 2022-05-25 01:11 UTC by gparvin

Templates in policies are useful to control content so policies can
contain dynamic instead of static content.  This can result in fewer
policies needed to cover a wider range of systems.

Refs:
 - https://github.com/stolostron/backlog/issues/22480

Signed-off-by: Gus Parvin <gparvin@redhat.com>

2022-05-25 01:20 UTC, mikeshng commented
/approve

@dhaiducek @mprahl could you please take a look?

2022-05-25 20:30 UTC, dhaiducek requested changes
Great additions--thanks, @gparvin!

I've made it halfway through and have dropped some comments for consideration. I'll complete the review shortly.

I wanted to stop to mention though that I think this section is getting lengthy, and I'm worried that users won't make it down to the installation easily. I wonder if all this content is better suited under "Concepts" (or as a sub-page) and we can link to that page from here? What do you think?

2022-05-25 20:30 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +Configuration policies support the inclusion of Golang text templates in the object definitions. These templates are resolved at runtime either on the hub cluster or the target managed cluster using
Please reflow this text so that it matches the line breaks in the surrounding text.

2022-05-25 20:30 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +Configuration policies support the inclusion of Golang text templates in the object definitions. These templates are resolved at runtime either on the hub cluster or the target managed cluster using
```suggestion
Configuration policies support the inclusion of Golang text templates in the object definitions. These templates are resolved at runtime either on the hub cluster or the target managed cluster using configurations related to that cluster. This gives you the ability to define configuration policies with dynamic content and to inform or enforce Kubernetes resources that are customized to the target cluster.
```

2022-05-25 20:30 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +* The template syntax must be conformed to the Golang template language specification, and the resource definition generated from the resolved template must be a valid YAML. See the Golang documentat
```suggestion
* The template syntax must follow the Golang template language specification, and the resource definition generated from the resolved template must be a valid YAML. (See the [Golang documentation about package templates](https://pkg.go.dev/text/template) for more information.) Any errors in template validation appear as policy violations. When you use a custom template function, the values are replaced at runtime.
```

2022-05-25 20:30 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +Template functions, such as resource-specific and generic, `lookup` template functions, are available for referencing Kubernetes resources on the cluster. The resource-specific functions are used for
```suggestion
Template functions, such as resource-specific and generic `lookup` template functions, are available for referencing Kubernetes resources on the cluster. The resource-specific functions are used for convenience and makes content of the resources more accessible. In addition to these functions, utility functions like `base64encode`, `base64decode`, `indent`, `autoindent`, `toInt`, `toBool`, and more are also available.
```

2022-05-25 20:30 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +To conform templates into YAML syntax, templates must be set in the policy resource as strings using quotes or a block character (`|` or `>`). This causes the resolved template value to also be a str
```suggestion
To conform templates to YAML syntax, templates must be set in the policy resource as strings using quotes or a block character (`|` or `>`). This causes the resolved template value to also be a string. To override this, consider using `toInt` or `toBool` as the final function in the template to initiate further processing that forces the value to be interpreted as an integer, or boolean.
```

2022-05-25 20:30 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +*Note*: If the string value is more than 80 characters, this block character, `|` needs to be used to avoid YAML parsing errors.
```suggestion
**Note**: If the string value is more than 80 characters, the block character `|` must be used to avoid YAML parsing errors.
```

2022-05-25 20:30 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +Alternatively, you can add the following annotation in the `ConfigurationPolicy` section of your `Policy`: `policy.open-cluster-management.io/disable-templates: "true"`. When this annotation is inclu
```suggestion
To bypass template processing for your hub cluster, you can either:
- Override a single template by wrapping the template in additional braces. For example, the template `{{ template content }}` would become `{{ '{{ template content }}' }}`.
- Override all templates in a `ConfigurationPolicy` by adding the `policy.open-cluster-management.io/disable-templates: "true"` annotation in the `ConfigurationPolicy` section of your `Policy`. Template processing will be bypassed for that `ConfigurationPolicy`.
```

2022-05-25 22:19 UTC, dhaiducek reviewed
Review, continued... 🙂

2022-05-25 22:19 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +| `toInt` | The `toInt` function casts and returns the integer value of the input value. Also, when this is the last function in the template, there is further processing of the source content. This
```suggestion
| `toInt` | Returns the integer value of the input string and ensures that the value is interpreted as an integer in the YAML. | `vlanid:  \|`<br />`{{ (fromConfigMap "site-config" "site1" "vlan")  \| toInt }}` |
```

2022-05-25 22:19 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +| `toBool` | The `toBool` function converts the input string into a boolean, and returns the boolean. Also, when this is the last function in the template, there is further processing of the source c
```suggestion
| `toBool` | Returns the boolean value of the input string and ensures that the value is interpreted as a boolean in the YAML. | `enabled:  \|`<br />`{{ (fromConfigMap "site-config" "site1" "enabled")  \| toBool }}` |
```

2022-05-25 22:19 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +| `protect` | The `protect` function enables you to encrypt a string in a hub cluster policy template. It is automatically decrypted on the managed cluster when the policy is evaluated. On the replic
```suggestion
| `protect` | Encrypts the input string. It is decrypted when the policy is evaluated. On the replicated policy in the managed cluster namespace, the resulting value might resemble the following: `$ocm_encrypted:okrrBqt72oI+3WT/0vxeI3vGa+wpLD7Z0ZxFMLvL204=` | `enabled: \|`<br />`{{hub "(lookup "v1" "Secret" "default" "my-hub-secret").data.message \| protect hub}}` |
```

2022-05-25 22:19 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +| `protect` | The `protect` function enables you to encrypt a string in a hub cluster policy template. It is automatically decrypted on the managed cluster when the policy is evaluated. On the replic
I don't think this is restricted to hub templates? Also, I think using `lookup "Secret"` with `protect` is somewhat of an antipattern since I think `fromSecret` should do protection, so probably use a different kind as above?

2022-05-25 22:19 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +To force an immediate rotation, delete the `policy.open-cluster-management.io/last-rotated` annotation on the `policy-encryption-key` Secret in the managed cluster namespace on the hub cluster. Polic
```suggestion
#### Template encryption details

The encryption algorithm uses AES-CBC with 256-bit keys. Each encryption key is unique per managed cluster and is automatically rotated every 30 days. This ensures that your decrypted value is never stored in the policy on the managed cluster.

To force an immediate encryption key rotation, delete the `policy.open-cluster-management.io/last-rotated` annotation on the `policy-encryption-key` Secret in the managed cluster namespace on the hub cluster. Policies are then reprocessed to use the new encryption key. 
```

2022-05-25 22:19 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +#### Hub cluster templates
I wonder if much of this section can be consolidated/simplified and moved up to the top "Policy Templates" section.

2022-05-26 20:21 UTC, gparvin commented on content/en/getting-started/integration/policy-framework.md
> +| `autoindent` | The `autoindent` function acts like the `indent` function that automatically determines the number of leading spaces based on the number of spaces before the template. | `Ca-cert:  \
Should be ok, getting ca certs to the right namespaces is valuable here.

2022-05-26 20:40 UTC, gparvin commented
Thanks for the great review Dale!  I've addressed your comments in the updated commit.

2022-05-31 14:20 UTC, mprahl commented on content/en/getting-started/integration/policy-framework.md
> +**Note**: If the string value is more than 80 characters, the block character `|`
This is no longer true in OCM 0.6.0. This can be removed.

2022-05-31 14:22 UTC, mprahl commented on content/en/getting-started/integration/policy-framework.md
> +On the managed cluster, the `ConfigurationPolicyController` processes any managed cluster
```suggestion
On the managed cluster, the Configuration Policy controller processes any managed cluster 
```

2022-05-31 15:30 UTC, gparvin commented
Thanks for the reviews @mprahl and @dhaiducek.  I believe I have addressed all of your comments.  Please take another look when you get a chance.

2022-05-31 15:35 UTC, mprahl approved these changes

2022-05-31 15:35 UTC, mprahl commented
/cc @mikeshng

2022-05-31 15:37 UTC, merged