add a doc to integrate OCM with Argo CD
open-cluster-management-io/open-cluster-management-io.github.io pull request #285
Opened 2022-08-29 14:01 UTC by elgnay

Signed-off-by: Yang Le <yangle@redhat.com>

2022-08-29 14:02 UTC, elgnay commented
/assign @haoqing0110 
/assign @qiujian16

2022-08-29 15:26 UTC, qiujian16 commented
i am thinking this is more appropriate to be put in the OCM repo, with a a runnable scripts

2022-08-29 16:34 UTC, mikeshng commented
I think we should have it in both places.

2022-08-30 14:00 UTC, elgnay commented
I created another PR https://github.com/open-cluster-management-io/OCM/pull/71 to add a new solution in OCM repo and will try to update this PR to reference to the new solution.

2022-09-07 08:01 UTC, qiujian16 commented
/assign @mikeshng

2022-09-07 18:21 UTC, mikeshng requested changes
Just some minor comments. Thank you for this doc!

2022-09-07 18:21 UTC, mikeshng commented on content/en/scenarios/integrate-with-argocd.md
> +**4. Binds at lease one clusterset to the `argocd` namespace.**
```suggestion
**4. Binds at least one managed clusterset to the `argocd` namespace.**
```

2022-09-07 18:21 UTC, mikeshng commented on content/en/scenarios/integrate-with-argocd.md
> +For example, in order to bind the `global` clusterset to the `argocd` namespace, the user must have an RBAC rule to `CREATE` on the virtual subresource of `managedclustersets/bind` of the `global` cl
```suggestion
For example, in order to bind the `global` managed clusterset to the `argocd` namespace, the user must have an RBAC rule to `create` on the virtual subresource of `managedclustersets/bind` of the `global` managed clusterset.
```

2022-09-07 18:21 UTC, mikeshng commented on content/en/scenarios/integrate-with-argocd.md
> +spec: {}
The empty object spec is a bit confusing for new users. 
Can we use some spec here like:
```
spec:
  numberOfClusters: 10
```

2022-09-07 18:21 UTC, mikeshng commented on content/en/scenarios/integrate-with-argocd.md
> +The `ApplicationSet` has references to the Cluster Decision Resource generator created previously and a placement. This will help Argo CD to determin where the application should be deployed. The man
```suggestion
The `ApplicationSet` has references to the previously created Cluster Decision Resource generator and placement. This will help Argo CD to determine where the application should be deployed. The managed clusters selected by the referenced placement may be changed dynamically. By setting `requeueAfterSeconds` of the generator in the `ApplicationSet` spec, the Argo CD will check the cluster decisions of the referenced placement periodically and ensure the application is deployed to the correct managed clusters.
```

2022-09-07 18:21 UTC, mikeshng commented on content/zh/scenarios/integrate-with-argocd.md
> +---
Please update ZH content if EN content changed. Thanks.

2022-09-07 18:21 UTC, mikeshng commented on i18n/en.toml
> +other = "Integrate with Argo CD"
```suggestion
other = "Integration with Argo CD"
```

2022-09-07 18:21 UTC, mikeshng commented on content/en/scenarios/integrate-with-argocd.md
> +### What's next
For this section, I think we are missing:

- Check ApplicationSet status to verify template is filled properly etc
- Check Application is created and verify status 
- Log onto managed cluster to see the app is successfully deployed

2022-09-07 18:21 UTC, mikeshng commented on content/en/scenarios/integrate-with-argocd.md
> +Follow the instructions on [Deploy applications with Argo CD](https://github.com/open-cluster-management-io/OCM/tree/main/solutions/deploy-argocd-apps) to build a OCM environment integrated with Argo
```suggestion
To build an OCM environment integrated with Argo CD with `KinD` clusters, see [Deploy applications with Argo CD](https://github.com/open-cluster-management-io/OCM/tree/main/solutions/deploy-argocd-apps) for more details.
```

2022-09-09 07:39 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +title: Integrate with Argo CD
Updated.

2022-09-09 07:39 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +Before starting with the following steps, suggest you understand the content below.
Updated.

2022-09-09 07:39 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +The OCM managed clusters can be registered to Argo CD one by one mannually by using Argo CD CLI. It may take time to finish it if there are a large number of clusters. In order to make the cluster re
Updated.

2022-09-09 07:39 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +**1. Import Kubernetes clusters to the OCM hub as managed clusters and organize them with clustersets.**
Updated.

2022-09-09 07:39 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +**4. Binds at lease one clusterset to the `argocd` namespace.**
Updated.

2022-09-09 07:39 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +The `ApplicationSet` has references to the Cluster Decision Resource generator created previously and a placement. This will help Argo CD to determin where the application should be deployed. The man
Updated.

2022-09-09 07:40 UTC, elgnay commented on content/zh/scenarios/integrate-with-argocd.md
> +---
Done.

2022-09-09 07:40 UTC, elgnay commented on i18n/en.toml
> +other = "Integrate with Argo CD"
Updated.

2022-09-09 07:40 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +### What's next
Added.

2022-09-09 07:40 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +Follow the instructions on [Deploy applications with Argo CD](https://github.com/open-cluster-management-io/OCM/tree/main/solutions/deploy-argocd-apps) to build a OCM environment integrated with Argo
Updated.

2022-09-09 07:40 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +For example, in order to bind the `global` clusterset to the `argocd` namespace, the user must have an RBAC rule to `CREATE` on the virtual subresource of `managedclustersets/bind` of the `global` cl
Updated.

2022-09-09 07:40 UTC, elgnay commented on content/en/scenarios/integrate-with-argocd.md
> +spec: {}
Updated.

2022-09-09 07:42 UTC, elgnay commented
> Just some minor comments. Thank you for this doc!

Updated the doc on your comments. Please take a look one more time. @mikeshng

2022-09-09 22:59 UTC, mikeshng approved these changes
/approve

/lgtm

2022-09-09 23:02 UTC, merged