Document the consolidated policy controller
open-cluster-management-io/open-cluster-management-io.github.io pull request #296
Opened 2022-10-14 15:38 UTC by mprahl

Relates:
https://github.com/stolostron/backlog/issues/25999

2022-10-14 15:39 UTC, mprahl commented
/cc @dhaiducek
/cc @mikeshng

2022-10-17 15:02 UTC, dhaiducek reviewed
LGTM! One minor question below.

I had two thoughts/questions on the structure of this doc:

1. I'm assuming the `clusteradm` commands will be addressed after those changes are made?
2. I was wondering whether the "install from source" should show how to install the addon controller instead, rather than drilling down to the individual controllers. I could see benefits either way, but I think I'm leaning toward keeping it this way since this truly is "the source".

2022-10-17 15:10 UTC, mprahl commented on content/en/getting-started/integration/policy-framework.md
> +     -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"governance-policy-framework-addon\",\"args\":[\"--hub-cluster-configfile=/var/run/klusterlet/kubeconfig\", \"--cluster-namespac
I believe the `clusteradm` change is already handled here:
https://github.com/open-cluster-management-io/clusteradm/pull/279

I like using arguments rather than environment variables since they are easily discoverable by using the `--help` flag and we get some free type validation from Go's standard library. I do agree that the patch command is rather ugly, but that's why you should use the addon controller, build a Helm chart, or build an Ansible playbook to deploy this rather than use the precanned `deploy/operator.yaml` file.

2022-10-17 17:50 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +     -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"governance-policy-framework-addon\",\"args\":[\"--hub-cluster-configfile=/var/run/klusterlet/kubeconfig\", \"--cluster-namespac
> I believe the `clusteradm` change is already handled here: [open-cluster-management-io/clusteradm#279](https://github.com/open-cluster-management-io/clusteradm/pull/279)

I hadn't seen that. In that case, would you please also update the `clusteradm` references to the sync controllers also?

> ...rather than use the precanned `deploy/operator.yaml` file.

Haha, that's fair. I was thinking we could use the env in the args, but your point is probably better.

2022-10-17 18:03 UTC, mprahl commented on content/en/getting-started/integration/policy-framework.md
> +     -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"governance-policy-framework-addon\",\"args\":[\"--hub-cluster-configfile=/var/run/klusterlet/kubeconfig\", \"--cluster-namespac
Thanks! I had totally missed that section. Oops.

2022-10-17 18:04 UTC, mprahl commented
/cc @dhaiducek 
/cc @mikeshng

2022-10-17 20:07 UTC, dhaiducek requested changes
LGTM! One minor change. After that, we'll need to hold this PR until the relevant versions of `clusteradm` and the OCM are released containing the code changes.

2022-10-17 20:08 UTC, dhaiducek commented
/hold for `v0.9.0`

2022-10-17 20:25 UTC, mprahl commented
> /hold for `v0.9.0`

@dhaiducek I'm not sure we can hold this because the docs use the main branch for installation from source. I could make a separate PR that changes the git ref from `main` to the latest tag.

2022-10-17 20:32 UTC, dhaiducek commented on content/en/governance-policy-framework-addon.md
> +---
Also, we don't want to get rid of the others since we still need the redirects to work.

2022-10-17 20:32 UTC, dhaiducek commented on content/en/governance-policy-framework-addon.md
> +---
...I think...I'm not 100% sure how all that works 🤷

2022-10-17 21:05 UTC, dhaiducek approved these changes

2022-10-24 15:03 UTC, dhaiducek commented
Once https://github.com/open-cluster-management-io/clusteradm/pull/280 merges and a new `clusteradm` is released, let's get this PR merged! Would you please rebase it in the meantime?

2022-10-24 18:09 UTC, dhaiducek requested changes
Thanks! Found a minor change.

2022-10-24 18:09 UTC, dhaiducek commented on content/zh/getting-started/integration/policy-framework.md
> +   [governance-policy-framework-addon controller](https://github.com/open-cluster-management-io/governance-policy-spec-sync)
```suggestion
   [governance-policy-framework-addon controller](https://github.com/open-cluster-management-io/governance-policy-framework-addon)
```

2022-10-24 18:57 UTC, mprahl commented
/cc @dhaiducek

2022-10-24 19:31 UTC, dhaiducek approved these changes

2022-10-24 19:34 UTC, mprahl commented
/cc @mikeshng

2022-10-24 19:52 UTC, mikeshng approved these changes
/lgtm

/approve

2022-10-24 20:32 UTC, mprahl commented
/unhold

2022-10-24 20:36 UTC, merged