Add release-0.9 notes
open-cluster-management-io/open-cluster-management-io.github.io pull request #305
Opened 2022-10-31 03:26 UTC by qiujian16

Signed-off-by: Jian Qiu <jqiu@redhat.com>

2022-10-31 18:56 UTC, dhaiducek requested changes
FYI @mprahl

2022-10-31 18:56 UTC, dhaiducek commented on content/en/community/releases.md
> +Open Cluster Management team is proud to annouce the release of OCM v0.9.0! Here are some main features included in this release:
```suggestion
Open Cluster Management team is proud to announce the release of OCM v0.9.0! Here are some main features included in this release:
```

2022-10-31 18:56 UTC, dhaiducek commented on content/en/community/releases.md
>  Open Cluster Management has approximately a three to four month release cycle. The current release is `v0.8.0`. Continue reading to view upcoming releases:
```suggestion
Open Cluster Management has approximately a three to four month release cycle. The current release is `v0.9.0`. Continue reading to view upcoming releases:
```

2022-10-31 18:56 UTC, dhaiducek commented on content/en/community/releases.md
> +  Update the ClusterSet API and gradually remove legacy custom resources, as well as allow for transformation of legacy resources into analogous v1beta2 resources. v1alpha1 APIs are removed.
```suggestion
  Update the ClusterSet API and gradually remove legacy custom resources, as well as allow for transformation of legacy resources into analogous v1beta2 resources. v1alpha1 APIs are removed.
- Consolidate the policy add-on template, status, and spec synchronization controllers into a single repository, [governance-policy-framework-addon](https://github.com/open-cluster-management-io/governance-policy-framework-addon)
```

2022-10-31 18:56 UTC, dhaiducek commented on content/en/community/releases.md
> +TBD
```suggestion
- config-policy-controller v0.9.0 [changelog](https://github.com/open-cluster-management-io/config-policy-controller/blob/main/CHANGELOG/CHANGELOG-v0.9.0.md)
- governance-policy-framework-addon v0.9.0 [changelog](https://github.com/open-cluster-management-io/governance-policy-framework-addon/blob/main/CHANGELOG/CHANGELOG-v0.9.0.md)
- governance-policy-propagator v0.9.0 [changelog](https://github.com/open-cluster-management-io/governance-policy-propagator/blob/main/CHANGELOG/CHANGELOG-v0.9.0.md)
- governance-policy-addon-controller v0.9.0 [changelog](https://github.com/open-cluster-management-io/governance-policy-addon-controller/blob/main/CHANGELOG/CHANGELOG-v0.9.0.md)
```

2022-11-02 13:34 UTC, dhaiducek reviewed
Thanks for the updates! One minor change to remove extra whitespace.

2022-11-02 13:34 UTC, dhaiducek commented on content/en/community/releases.md
> +- Consolidate the policy add-on template, status, and spec synchronization controllers into a single repository,   [governance-policy-framework-addon](https://github.com/open-cluster-management-io/go
```suggestion
- Consolidate the policy add-on template, status, and spec synchronization controllers into a single repository, [governance-policy-framework-addon](https://github.com/open-cluster-management-io/governance-policy-framework-addon)
```

2022-11-03 15:25 UTC, mikeshng reviewed
Added app-addon notes. FYI @xiangjingli

2022-11-03 15:25 UTC, mikeshng commented on content/en/community/releases.md
> +- Consolidate the policy add-on template, status, and spec synchronization controllers into a single repository,  [governance-policy-framework-addon](https://github.com/open-cluster-management-io/gov
```suggestion
- Consolidate the policy add-on template, status, and spec synchronization controllers into a single repository, [governance-policy-framework-addon](https://github.com/open-cluster-management-io/governance-policy-framework-addon)
- Application add-on is now able to expose custom Prometheus metrics via the Git subscription. See the [metric documentation](https://github.com/open-cluster-management-io/multicloud-operators-subscription/blob/v0.9.0/docs/metrics.md) for more details.
```

2022-11-03 15:25 UTC, mikeshng commented on content/en/community/releases.md
> +
```suggestion
- multicloud-operators-subscription v0.9.0 [release note](https://github.com/open-cluster-management-io/multicloud-operators-subscription/releases/tag/v0.9.0)
- multicloud-operators-channel v0.9.0 [release note](https://github.com/open-cluster-management-io/multicloud-operators-channel/releases/tag/v0.9.0)
- multicloud-integrations v0.9.0 [release note](https://github.com/open-cluster-management-io/multicloud-integrations/releases/tag/v0.9.0)
```

2022-11-03 15:27 UTC, mikeshng commented
https://www.cncf.io/blog/2022/10/31/open-cluster-management-november-2022-update/

CNCF blog post for reference.

2022-11-04 09:01 UTC, yue9944882 commented
LGTM

2022-11-07 18:31 UTC, mikeshng commented
Not sure what happen I see a commit https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/commit/513cc83322122ab8f07922cc8febc29c371677f1 which contains the app addon changes but when I click Files Changes I don't see it.

2022-11-10 14:07 UTC, mikeshng approved these changes
/lgtm

2022-11-10 14:12 UTC, merged