Release note 0.10.0
open-cluster-management-io/open-cluster-management-io.github.io pull request #330
Opened 2023-02-17 07:08 UTC by qiujian16

2023-02-17 16:29 UTC, dhaiducek requested changes

2023-02-17 16:29 UTC, dhaiducek commented on content/en/community/releases.md
> +
```suggestion
- A Policy or ConfigurationPolicy can specify dependencies on another policy having a specified status before taking action.
- A raw string with go templates can be provided in `object-templates-raw` to the ConfigurationPolicy, allowing dynamically generated objects through the use of functions like `{{ range ... }}`.

```

2023-02-20 00:29 UTC, mikeshng commented on content/en/community/releases.md
> +- Policy templating is enhanced so that when a referenced object is updated, the template is also updated.
```suggestion
- Argo CD hub-spoke / pull model application delivery integration. See [argocd-pull-integration repo](https://github.com/open-cluster-management-io/argocd-pull-integration) for more details.
- Policy templating is enhanced so that when a referenced object is updated, the template is also updated.
```

2023-02-20 01:31 UTC, qiujian16 commented
thanks, need to signoff the commit :)

2023-02-27 08:28 UTC, ldpliu commented
/lgtm

2023-02-27 08:33 UTC, merged