correct document spelling issues
open-cluster-management-io/open-cluster-management-io.github.io pull request #332
Opened 2023-02-21 10:42 UTC by yanmxa

Signed-off-by: myan [myan@redhat.com](mailto:myan@redhat.com)

2023-02-21 14:03 UTC, dhaiducek requested changes
Thanks for the PR, @yanmxa! Would you please make the equivalent changes in the `en` and `zh` folders?

2023-02-21 14:03 UTC, dhaiducek commented on content/zh/getting-started/integration/cluster-proxy.md
> +control plane network connectivity for us:
Please also update the `content/en` directory with this change.

2023-02-21 14:03 UTC, dhaiducek commented on content/en/concepts/managedcluster.md
> +resource. The cluster will be accepted by the hub control plane, if the
Please also update the `content/zh` directory with this change.

2023-02-22 01:47 UTC, yanmxa commented on content/zh/getting-started/integration/cluster-proxy.md
> +control plane network connectivity for us:
Done!

2023-02-22 01:47 UTC, yanmxa commented on content/en/concepts/managedcluster.md
> +resource. The cluster will be accepted by the hub control plane, if the
It's right in the `content/zh`.

2023-02-22 02:04 UTC, mikeshng approved these changes
/approve

/lgtm

2023-02-22 02:09 UTC, merged