add alt to img
open-cluster-management-io/open-cluster-management-io.github.io pull request #348
Opened 2023-05-04 01:54 UTC by Arhell

resolve https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/347

2023-05-04 12:29 UTC, mikeshng requested changes
Thank you for your contribution! 
Just some minor nits.

2023-05-04 12:29 UTC, mikeshng commented on themes/ocmTheme/layouts/partials/supports.html
> +        <a class="supports-logo" href="https://www.alibabacloud.com/" title="Alibab Cloud" target="_blank"><img src="/alibaba-cloud.svg" alt="Alibaba cloud" /></a>
```suggestion
        <a class="supports-logo" href="https://www.alibabacloud.com/" title="Alibab Cloud" target="_blank"><img src="/alibaba-cloud.svg" alt="Alibaba Cloud" /></a>
```

2023-05-04 12:29 UTC, mikeshng commented on themes/ocmTheme/layouts/partials/supports.html
> +        <a class="supports-logo" href="https://www.antgroup.com/" title="Ant Group" target="_blank"><img src="/ant-group.svg" alt="Ant group" /></a>
```suggestion
        <a class="supports-logo" href="https://www.antgroup.com/" title="Ant Group" target="_blank"><img src="/ant-group.svg" alt="Ant Group" /></a>
```

2023-05-04 12:29 UTC, mikeshng commented on themes/ocmTheme/layouts/partials/supports.html
> +        <a class="supports-logo" href="https://www.redhat.com/" title="Red Hat" target="_blank"><img src="/red-hat.svg" alt="Red hat" /></a>
```suggestion
        <a class="supports-logo" href="https://www.redhat.com/" title="Red Hat" target="_blank"><img src="/red-hat.svg" alt="Red Hat" /></a>
```

2023-05-04 12:29 UTC, mikeshng commented on themes/ocmTheme/layouts/partials/supports.html
> +        <a class="supports-logo tencent-logo" href="https://cloud.tencent.com/" title="Tencent Cloud" target="_blank"><img src="/tencent-cloud.svg" alt="Tencent cloud" /></a>
```suggestion
        <a class="supports-logo tencent-logo" href="https://cloud.tencent.com/" title="Tencent Cloud" target="_blank"><img src="/tencent-cloud.svg" alt="Tencent Cloud" /></a>
```

2023-05-04 12:29 UTC, mikeshng commented
/assign @chenz4027

2023-05-05 00:21 UTC, Arhell commented on themes/ocmTheme/layouts/partials/supports.html
> +        <a class="supports-logo" href="https://www.alibabacloud.com/" title="Alibab Cloud" target="_blank"><img src="/alibaba-cloud.svg" alt="Alibaba cloud" /></a>
Done

2023-05-05 00:21 UTC, Arhell commented on themes/ocmTheme/layouts/partials/supports.html
> +        <a class="supports-logo" href="https://www.antgroup.com/" title="Ant Group" target="_blank"><img src="/ant-group.svg" alt="Ant group" /></a>
Done

2023-05-05 00:21 UTC, Arhell commented on themes/ocmTheme/layouts/partials/supports.html
> +        <a class="supports-logo" href="https://www.redhat.com/" title="Red Hat" target="_blank"><img src="/red-hat.svg" alt="Red hat" /></a>
Done

2023-05-05 00:21 UTC, Arhell commented on themes/ocmTheme/layouts/partials/supports.html
> +        <a class="supports-logo tencent-logo" href="https://cloud.tencent.com/" title="Tencent Cloud" target="_blank"><img src="/tencent-cloud.svg" alt="Tencent cloud" /></a>
Done

2023-05-05 00:51 UTC, mikeshng commented
/approve

@chenz4027 please take a quick look whenever you have some cycles. Thanks!

2023-05-25 01:27 UTC, qiujian16 commented
/lgtm

2023-05-25 01:32 UTC, merged