add  0.12 release note
open-cluster-management-io/open-cluster-management-io.github.io pull request #389
Opened 2023-10-11 07:45 UTC by qiujian16

2023-10-12 01:59 UTC, zhujian7 commented
@qiujian16 for managed-serviceaccount addon:
- we added a new version v1beta1 for managed service account API: https://github.com/open-cluster-management-io/managed-serviceaccount/pull/78
- support using addon template to deploy agent: https://github.com/open-cluster-management-io/managed-serviceaccount/pull/69

2023-10-12 02:13 UTC, xuezhaojun commented
@qiujian16 No significant upgrades in cluster-proxy

2023-10-12 16:43 UTC, dhaiducek requested changes
Thanks for creating this PR! I have some wording suggestions on current content as well as Policy additions.

2023-10-12 16:43 UTC, dhaiducek commented on content/en/community/releases.md
> +thie release
```suggestion
The Open Cluster Management team is proud to announce the release of OCM v0.12.0! We have made architecture refactors and added several features in
this release:
```

2023-10-12 16:43 UTC, dhaiducek commented on content/en/community/releases.md
> +- Singleton agent mode: user can now choose to start agent as a single pod using the `Singleton` mode in the klusterlet.
```suggestion
- Component consolidation: we made a big code refactor to merge code in registraton, work, placement and registration-operator into the [ocm](https://github.com/open-cluster-management-io/ocm) repo.
  The original separated code repos are currently used for maintaining old releases only. This code consolidation allows us to build more robust e2e tests, and build a single
  agent binary to reduce the footprint in managed clusters.
- Addon Template API: A new `addontemplate` API is introduced to ease the development of addons. Users will not need to write code and run an addon-manager
  controller on the hub cluster. Instead, they only need to define the `addontemplate` API to create an addon. `clusteradm` also has a new command
  `clusteradm addon create ...` to create an addon from resource manifests files. See more details about `addontemplate` in the  
  [addon documentation](https://open-cluster-management.io/developer-guides/addon/#build-an-addon-with-addon-template).
- Singleton agent mode: users can now choose to start the agent as a single pod using the `Singleton` mode in the klusterlet.
```

2023-10-12 16:43 UTC, dhaiducek commented on content/en/community/releases.md
> +TBD
```suggestion
- config-policy-controller v0.12.0 [changelog](https://github.com/open-cluster-management-io/config-policy-controller/releases/tag/v0.12.0)
- governance-policy-framework-addon v0.12.0 [changelog](https://github.com/open-cluster-management-io/governance-policy-framework-addon/releases/tag/v0.12.0)
- governance-policy-propagator v0.12.0 [changelog](https://github.com/open-cluster-management-io/governance-policy-propagator/releases/tag/v0.12.0)
- governance-policy-addon-controller v0.12.0 [changelog](https://github.com/open-cluster-management-io/governance-policy-addon-controller/releases/tag/v0.12.0)
```

2023-10-12 16:43 UTC, dhaiducek commented on content/en/community/releases.md
> +
```suggestion
- `Policy`: Add the `informOnly` option to `remediationAction` in `ConfigurationPolicy`, signaling that the remediation action set on the `Policy` should not override the `ConfigurationPolicy`'s remediation action.
- `Policy`: Security, performance, and stability improvements in controllers on both the hub and managed clusters.

```

2023-10-12 16:43 UTC, dhaiducek commented on content/en/community/releases.md
> +## `0.12.0`, 11, Oct. 2023
```suggestion
## `0.12.0`, 11 Oct. 2023
```

2023-10-13 17:37 UTC, mikeshng commented on content/en/community/releases.md
> +TBD
```
- multicloud-operators-subscription v0.12.0 [release note](https://github.com/open-cluster-management-io/multicloud-operators-subscription/releases/tag/v0.12.0)
- multicloud-operators-channel v0.12.0 [release note](https://github.com/open-cluster-management-io/multicloud-operators-channel/releases/tag/v0.12.0)
- multicloud-integrations v0.12.0 [release note](https://github.com/open-cluster-management-io/multicloud-integrations/releases/tag/v0.12.0)
```
Please add app addons as well.

2023-10-13 17:39 UTC, mikeshng commented on content/en/community/releases.md
> +TBD
^ Added app addons as well in the above suggestion.

2023-10-13 18:21 UTC, mikeshng commented on content/en/community/releases.md
> +
^ Added ClusterPermission to the above suggestion.

2023-10-17 02:10 UTC, qiujian16 commented
> @qiujian16 for managed-serviceaccount addon:
> 
> * we added a new version v1beta1 for managed service account API: [add v1beta1 managed service account managed-serviceaccount#78](https://github.com/open-cluster-management-io/managed-serviceaccount/pull/78)
> * support using addon template to deploy agent: [support using addon template to deploy agent managed-serviceaccount#69](https://github.com/open-cluster-management-io/managed-serviceaccount/pull/69)

@zhujian7 could you propose a change on the existing PR? thanks!

2023-10-18 02:35 UTC, zhujian7 commented on content/en/community/releases.md
> +
```suggestion
- managed-serviceaccount v0.4.0 [changelog](https://github.com/open-cluster-management-io/managed-serviceaccount/releases/tag/v0.4.0)
```

2023-10-18 08:40 UTC, qiujian16 commented
all is resolved @mikeshng would you like to take another look and tag it?

2023-10-18 13:59 UTC, dhaiducek requested changes

2023-10-18 13:59 UTC, dhaiducek commented on content/en/community/releases.md
> +thie release:
```suggestion
this release:
```

2023-10-18 13:59 UTC, dhaiducek commented on content/en/community/releases.md
> +- Component consolidation: we made a big code refactor to merge code in registraton, work, placement and registration-operator into the [ocm](https://github.com/open-cluster-management-io/ocm) repo.
```suggestion
- Component consolidation: we made a big code refactor to merge code in registration, work, placement and registration-operator into the [ocm](https://github.com/open-cluster-management-io/ocm) repo.
```

2023-10-18 13:59 UTC, dhaiducek commented on content/en/community/releases.md
> +
I don't see this `managed-serviceaccount` addition in `content/en`, only `content/zh`?

2023-10-19 01:11 UTC, zhujian7 commented on content/en/community/releases.md
> +
yes @qiujian16 please also add it into `content/en`

2023-10-19 13:18 UTC, mikeshng commented
> all is resolved @mikeshng would you like to take another look and tag it?

Oops. I used the GitHub UI to commit suggestion and now it's failing DCO. Could you help force push please? Thanks.

2023-10-19 13:47 UTC, qiujian16 commented
updated

2023-10-19 14:03 UTC, mikeshng approved these changes
/approve

/lgtm

2023-10-19 14:09 UTC, dhaiducek commented on content/en/community/releases.md
> +- Component consolidation: we made a big code refactor to merge code in registraton, work, placement and registration-operator into the [ocm](https://github.com/open-cluster-management-io/ocm) repo.
```suggestion
- Component consolidation: we made a big code refactor to merge code in registration, work, placement and registration-operator into the [ocm](https://github.com/open-cluster-management-io/ocm) repo.
```

2023-10-19 14:10 UTC, dhaiducek commented on content/en/community/releases.md
> +
@qiujian16 The `managed-serviceaccount` is still missing from `content/en`

2023-10-19 14:10 UTC, merged

2023-10-19 14:11 UTC, dhaiducek commented
Sorry, I wasn't fast enough 😢

2023-10-19 14:16 UTC, dhaiducek commented
I've created a followup PR to address the review comments:
- https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/390