Release announcement for 0.13.0
open-cluster-management-io/open-cluster-management-io.github.io pull request #409
Opened 2024-03-06 07:12 UTC by qiujian16

2024-03-07 08:29 UTC, zhujian7 commented
I think we should mention that when upgrading addon-framework to 0.9.0, [`patch` `clustermanagementaddon` permission should be added](https://github.com/open-cluster-management-io/addon-framework/pull/236#discussion_r1475478681).

2024-03-11 01:31 UTC, zhujian7 commented on content/en/community/releases.md
> +- Addon-framework is upgraded to v0.9.0 to better support generic addon-manager and addon rolling out strategy. It is highly
should we mention that `patch clustermanagementaddon permisson` should be added after upgrading to 0.9.0`?

2024-03-11 19:39 UTC, mikeshng reviewed
Just want to highlight an app addon feature. The rest LGTM.

2024-03-11 19:39 UTC, mikeshng commented on content/en/community/releases.md
> +  the upgrade.
```suggestion
  the upgrade. 
  - Application add-on `Subscription` API can now aggregate and report managed clusters' kustomization errors.
```

2024-03-12 11:28 UTC, dhaiducek requested changes
Thanks! Sorry for my belated review. I've added a couple bullets for Policy as well as suggested some other spelling/wording edits.

2024-03-12 11:28 UTC, dhaiducek commented on content/en/community/releases.md
> +  details.
```suggestion
- Rollout API: we built a common rollout API that has been adopted in `ClusterManagementAddon` and `ManifestWorkReplicaSet`,
  and will be also used in the policy addon in a future release. The API provides users a way to define a workload/addon rolling upgrade strategy
  across multiple clusters. See [here](https://open-cluster-management.io/concepts/addon/#add-on-rollout-strategy) for more
  details.
```

2024-03-12 11:28 UTC, dhaiducek commented on content/en/community/releases.md
> +  resource request, QPS/Burst and priority class.
```suggestion
- More install configurations in Klusterlet: we enhanced the `Klusterlet` API by adding more configuration fields, including
  resource requests, QPS/Burst and priority class.
```

2024-03-12 11:28 UTC, dhaiducek commented on content/en/community/releases.md
> +  for more details.
```suggestion
- Cloudevent support: an experimental feature to wire the work agent with a message broker using the cloudevent protocol. This enables a
  work agent running in a highly scalable mode. See [here](
  https://github.com/open-cluster-management-io/enhancements/tree/main/enhancements/sig-architecture/224-event-based-manifestwork)
  for more details.
```

2024-03-12 11:28 UTC, dhaiducek commented on content/en/community/releases.md
> +  the upgrade.
```suggestion
- Addon-framework is upgraded to v0.9.0 to better support the generic addon-manager and addon rolling out strategy. It is highly
  recommended for addons to upgrade the addon-framework depdency to version v0.8.1 or higher. Also it should be noted that an
 RBAC update of the addon hub controller (adding PATCH for resource `clustermanagementaddons`) is required during
  the upgrade. 
```

2024-03-12 11:28 UTC, dhaiducek commented on content/en/community/releases.md
> +
@mprahl Do you want to mention the Compliance History API here or do we need to make sure all the pieces are in place in this release before announcing it anywhere?

```suggestion
- New OperatorPolicy to handle OLM operators: A new OperatorPolicy is added, managed by the `config-policy-controller` Pod, aimed at easing the management of OLM deployments.
- Diff logging for ConfigurationPolicy: A `recordDiff` parameter is added to `ConfigurationPolicy` to enable the diff between the object on the cluster and the policy definition to be logged in the `config-policy-controller` Pod logs.

```

2024-03-12 13:28 UTC, mprahl commented on content/en/community/releases.md
> +
@dhaiducek I think we can announce it here, but I'll create an issue to add documentation in OCM-io on it.

2024-03-12 14:28 UTC, dhaiducek commented on content/en/community/releases.md
> +
Thanks--compliance history added!

2024-03-12 14:32 UTC, dhaiducek commented on content/en/community/releases.md
> +  recommended for addons to upgrade the addon-framework depdency to version v0.8.1 or higher. Also, it should be noted that
```suggestion
  recommended for addons to upgrade the addon-framework dependency to version v0.8.1 or higher. Also, it should be noted that
```

2024-03-15 02:02 UTC, mikeshng approved these changes
/approve

/lgtm

2024-03-15 02:02 UTC, mikeshng commented
/unhold

2024-03-15 02:06 UTC, merged