Relase note for v0.14.0
open-cluster-management-io/open-cluster-management-io.github.io pull request #421
Opened 2024-06-26 09:21 UTC by qiujian16

2024-06-26 09:22 UTC, qiujian16 commented
/assign @mikeshng @dhaiducek 

Please check if anything needs to be added.

2024-06-26 21:53 UTC, mikeshng commented on content/en/community/releases.md
> +- multicloud-integrations v0.14.0 [changelog](https://github.com/open-cluster-management-io/multicloud-integrations/releases/tag/v0.14.0)
```suggestion
```

The app team is planning to archive this repo on ocm-io.

2024-07-03 19:38 UTC, dhaiducek requested changes
Sorry for the delay! I have one comment on wording and one comment on adding Policy Framework updates.

2024-07-03 19:38 UTC, dhaiducek commented on content/en/community/releases.md
> +from cluster-api management cluster with `--capi-import` and  `--capi-cluster-name` flag.
Adding Policy updates:
```suggestion
- Exclude terminating clusters from Placementdecision: now cluster in terminating state will not be picked by the
placement.
- Send available condition events for managed cluster: klusterlet agent will send kubenerte event to the cluster
namespace upon status change, which makes it eaiser for user to check the state change of the managed cluster.
- Set install namespace of addonTemplate from addonDeploymentConfig: user of AddonTemplate API can now use 
AddonDeploymentConfig API to set the installation namespace of the agent.
- Configurable controller replicas and master node selector: user can not set flags `deployment-replicas` and
`control-plane-node-label-selector` on klusterlet-operator to customize the replicas of the klusterlet agent.
- Add capi into join flow: user can now use the join command to add a cluster-api provisioned cluster into ocm hub
from cluster-api management cluster with `--capi-import` and  `--capi-cluster-name` flag.
- (Policy Framework) `OperatorPolicy` enhancement and stabilization: OperatorPolicy can now be set to `mustnothave` to perform cleanup, alongside stabilization improvements.
- (Policy Framework) Add `ConfigurationPolicy` diff to the status: Adds a `recordDiff: InStatus` as the default value if it's not set. In this mode, the difference between the policy and the object on the managed is returned in the status. Sensitive data types are not displayed unless `InStatus` is explicitly provided.
- (Policy Framework) Add `recreateOption` to `ConfigurationPolicy`: When a user needs to update an object with immutable fields, the object must be replaced. In this case, `recreateOption` can be set to either `ifRequired` or `Always` depending on the requirements.
```

2024-07-04 13:01 UTC, mikeshng commented
Looks good leaving it to Dale for a final look. Thanks.

2024-08-13 21:01 UTC, dhaiducek approved these changes
Oh no! I didn't realize this was still hanging out here. Approving.

2024-08-13 21:03 UTC, merged