Add release note for 0.15.0
open-cluster-management-io/open-cluster-management-io.github.io pull request #434
Opened 2024-10-24 08:33 UTC by qiujian16

2024-10-24 08:34 UTC, qiujian16 commented
/assign @mikeshng 
/assign @dhaiducek

2024-10-24 08:34 UTC, qiujian16 commented
/assign @tamalsaha

2024-10-29 12:30 UTC, mikeshng reviewed
Current native app-addon is in maintenance mode and soon to be replaced by another app integration. So there weren’t any significant updates for this release besides bug fixes.

Leaving Lgeetm to Dale. Thanks.

2024-10-30 01:36 UTC, dhaiducek requested changes
Sorry for the delay here! I've noted some tweaks and added Policy content.

2024-10-30 01:36 UTC, dhaiducek commented on content/en/docs/release/_index.md
> +  [here](https://github.com/kubernetes-sigs/cluster-inventory-api) for more details on cluster inventory API.
````suggestion
  [here](https://github.com/kubernetes-sigs/cluster-inventory-api) for more details on cluster inventory API.
- (Policy framework) Event-driven `ConfigurationPolicy` evaluations: By default, `ConfigurationPolicy` reconciles are now event-driven, lowering resource consumption and increasing efficiency. Users can set a policy to reconcile on an interval as they were previously by configuring `spec.evaluationInterval`.
- (Policy framework) Custom `ConfigurationPolicy` compliance messages: Policy authors can now define Go templates to be used for compliance messages, including `.DefaultMessage` and `.Policy` fields available for parsing relevant information.
- (Policy framework) `dryrun` CLI: A `dryrun` CLI is available to reconcile `ConfigurationPolicy` locally, allowing you to view the compliance and diff resulting from a `ConfigurationPolicy` without deploying it to a cluster:
  ```
  go install open-cluster-management.io/config-policy-controller/cmd/dryrun@latest
  ```
- (Policy framework) Customizable hub cluster template access: Users can now set `spec.hubTemplateOptions.serviceAccountName` to leverage a service account in the root policy namespace to resolve hub templates. Without the service account, hub templates are only able to access objects in the same namespace as the policy.
````

2024-10-30 02:13 UTC, qiujian16 commented
> Sorry for the delay here! I've noted some tweaks and added Policy content.

@dhaiducek PTAL again, thanks!

2024-10-30 13:44 UTC, dhaiducek commented on content/en/docs/release/_index.md
> +  an out of date configuration being picked to deploy the addon agent..
```suggestion
  an out of date configuration being picked to deploy the addon agent.
```

2024-10-30 13:45 UTC, dhaiducek approved these changes
/hold If you want to remove the extra period.

LGTM! Thanks for the update!

2024-10-31 06:53 UTC, xuezhaojun commented
/lgtm

2024-10-31 08:05 UTC, qiujian16 commented
/unhold

2024-10-31 08:09 UTC, merged