Instructions to try aws based registration manually
open-cluster-management-io/open-cluster-management-io.github.io pull request #438
Opened 2024-12-05 23:09 UTC by jaswalkiranavtar

2024-12-06 01:30 UTC, mikeshng commented on content/en/blog/joining-hub-and-spoke-with-aws-auth-manually/index.md
> +   sed -e "s/PROVIDER_ID/$SPOKE_OIDC_PROVIDER_ID/g" -e "s/ACCOUNT_ID/$SPOKE_ACCOUNT_ID/g" -e "s/REGION/$SPOKE_REGION/g" templates/Template-Spoke-Role-Trust-Policy.json > templates/Spoke-Role-Trust-Po
I am not sure if this is the best place to hold the `templates` folder. 
Maybe https://github.com/open-cluster-management-io/ocm/tree/main/solutions makes more sense? @qiujian16 @xuezhaojun WDYT?

2024-12-06 02:14 UTC, qiujian16 commented on content/en/blog/joining-hub-and-spoke-with-aws-auth-manually/index.md
> +   sed -e "s/PROVIDER_ID/$SPOKE_OIDC_PROVIDER_ID/g" -e "s/ACCOUNT_ID/$SPOKE_ACCOUNT_ID/g" -e "s/REGION/$SPOKE_REGION/g" templates/Template-Spoke-Role-Trust-Policy.json > templates/Spoke-Role-Trust-Po
yes, I agree.

2024-12-06 19:12 UTC, suvaanshkumar commented on content/en/blog/joining-hub-and-spoke-with-aws-auth-manually/index.md
> +   sed -e "s/PROVIDER_ID/$SPOKE_OIDC_PROVIDER_ID/g" -e "s/ACCOUNT_ID/$SPOKE_ACCOUNT_ID/g" -e "s/REGION/$SPOKE_REGION/g" templates/Template-Spoke-Role-Trust-Policy.json > templates/Spoke-Role-Trust-Po
Created [PR](https://github.com/open-cluster-management-io/ocm/pull/749/files)

2024-12-09 16:14 UTC, mikeshng requested changes

2024-12-09 19:25 UTC, jaswalkiranavtar commented on content/en/blog/joining-hub-and-spoke-with-aws-auth-manually/index.md
> +   sed -e "s/PROVIDER_ID/$SPOKE_OIDC_PROVIDER_ID/g" -e "s/ACCOUNT_ID/$SPOKE_ACCOUNT_ID/g" -e "s/REGION/$SPOKE_REGION/g" templates/Template-Spoke-Role-Trust-Policy.json > templates/Spoke-Role-Trust-Po
Moved

2024-12-09 19:37 UTC, mikeshng approved these changes
/approve

/lgtm

Thanks!

2024-12-09 19:39 UTC, merged