Add clusteradm instruction
open-cluster-management-io/open-cluster-management-io.github.io pull request #90
Opened 2021-06-14 13:44 UTC by itdove

Signed-off-by: Dominique Vernier <dvernier@redhat.com>

2021-06-14 14:54 UTC, mikeshng commented
I know I said use 1. 2. in slack but after looking at the page rendered, it makes it look like step 1 and then step 2. How about the below:
I will slack you the actual code. We should probably get the doc team to look at it as well. I will link this issue in the doc defect when we are ready.

![image](https://user-images.githubusercontent.com/58747157/121912604-b8419f80-ccfe-11eb-97ee-c6c91e922288.png)

2021-06-14 19:33 UTC, cadawson commented
I might be a little early on this one, but a couple of comments:

Use either of the following methods to bootstrap your Open Cluster Management environment: 

- Clusteradn CLI tool
- OperatorHub

Clusteradm CLI tool
Run the following command to bootstrap your Open Cluster Management environment by using the CLI:

```
clusteradm.init
```
For more details, see the clusteradm GitHub page. 

OperatorHub

1. Install and create a cluster manager on your hub cluster.
2. Install and create a klusterlet agent on your managed cluster.

For more details, see Core components.  

**CD** The link to Core components is sending me a 404.

2021-06-14 20:01 UTC, mikeshng commented
> The link to Core components is sending me a 404.

Thanks for the review. You have to clone the repo locally and `make server` then browse to http://localhost:1313/ to check the links is working properly or not. It's using the `hugo` framework to render the webpage so just using an IDE's preview md to click the links might not work properly. The hugo framework will take care of the linkage after it builds. For example, after build it becomes like this https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/blob/gh-pages/getting-started/quick-start/index.html#L241-L243

2021-06-15 02:27 UTC, qiujian16 commented on content/getting-started/quick-start/_index.md
> +```bash
add a download command here also. 

I think we also need to doc how to join? Are you going to add it in another PR

2021-06-15 14:07 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +```bash
I think originally we had download and uncompressed commands but then instructions gotten really complicated between different OS.
Maybe we just assume its a Linux/MacOS environment and do something like this?

```
curl someflag someurl | tar -xz  -C /tmp/ # For Linux OS, see more details for other OSes.
cd /tmp
mv clusteradm-xyz clusteradm
./clusteradm init
```
What do you guys think?

2021-06-15 15:57 UTC, dockerymick requested changes

2021-06-15 15:57 UTC, dockerymick commented on content/getting-started/quick-start/_index.md
> +## Operator Hub
Add a new line break between the end of the reference link on line 14 and the section title Operator hub

Please also use a lowercase h

2021-06-15 15:57 UTC, dockerymick commented on content/getting-started/quick-start/_index.md
>  ![open-cluster-management](/ocm-logo.png)
The image is not rendering here

2021-06-15 15:57 UTC, dockerymick commented on content/getting-started/quick-start/_index.md
>  Install and create a [Cluster manager](https://operatorhub.io/operator/cluster-manager) on your _hub_ cluster.
Are these prerequisites or steps?

2021-06-22 07:39 UTC, qiujian16 commented on content/getting-started/quick-start/_index.md
> +```bash
we could take linux os as an example, ideally, there should be a box that we could switch among platforms

2021-06-22 11:01 UTC, itdove commented
The original idea was to have all platforms method for download, but then we decided to have just a light how to join explanation here and the full explanation in the GitHub readme as not necessarily all user will pass by this website and we didn't want to maintain 2 locations for the quick-start (this website and the readme)

2021-06-23 14:23 UTC, qiujian16 commented
/approve

@mikeshng leave lgtm to you

2021-06-23 14:24 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
>  Install and create a [Cluster manager](https://operatorhub.io/operator/cluster-manager) on your _hub_ cluster.
no these are not prereqs steps just quick summary of what the command does and for more details refer to github link

2021-06-23 14:25 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
>  ![open-cluster-management](/ocm-logo.png)
should be ok. its just not rendering ok your ide but it will be fine if you have a hugo framework installed and you run make build.

2021-06-23 14:26 UTC, mikeshng commented on content/getting-started/quick-start/_index.md
> +## Operator Hub
@itdove can you fix this in your fork branch? 

- Operator Hub should be `Operator hub`
- and add the space as suggested.

2021-06-23 14:26 UTC, mikeshng commented
I think we should adjust the review feedback for https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/90#discussion_r657156553 and we should be good to go

2021-06-23 14:31 UTC, itdove commented on content/getting-started/quick-start/_index.md
> +## Operator Hub
Done

2021-06-23 14:36 UTC, mikeshng commented
/lgtm

2021-06-23 14:36 UTC, merged