Add placement design
open-cluster-management-io/open-cluster-management-io.github.io pull request #99
Opened 2021-06-25 07:23 UTC by qiujian16

Signed-off-by: Jian Qiu <jqiu@redhat.com>

2021-06-25 07:36 UTC, xuezhaojun commented on content/concepts/placement.md
> +You must have the `create` permision on resource `managedclusterset/bind` to bind the `ManagedClusterSet` to a namespace.
permission

2021-06-25 08:34 UTC, qiujian16 commented
/assign @mikeshng

2021-06-25 13:26 UTC, mikeshng requested changes

2021-06-25 13:26 UTC, mikeshng commented on content/concepts/placement.md
> +A slice of `PlacementDecision` will be created by placement controller in the same namespace, each with a label of `open-cluster-management.io/placemeent=placement1`. `PlacementDecision` contains the
`placemeent` should probably be `placement`

2021-06-25 13:50 UTC, swopebe commented on content/concepts/placement.md
> +`Placement` API is to select a set of managed clusters in one or multiple `ManagedClusterSets`, so that the user's workloads can be deployed to these clusters.
`Placement` API is **used** to select a set of managed clusters in one or multiple `ManagedClusterSets` so that the user workloads can be deployed to these clusters.

See change in **bold,** then see I got rid of comma.

2021-06-25 13:53 UTC, swopebe commented on content/concepts/placement.md
> +Before creating a `Placement`, you need to bind a `ManagedClusterSet` which is cluster scoped to a namespace by creating a `ManagedClusterSetBinding` in this namespace. Then you can create a `Placeme
Confusing line:

Are you telling them they need to:

Create a `ManagedClusterSetBinding` in this namespace.

Or it is bound by "creating"...? If the first, let's just make it an active sentence.

2021-06-25 13:53 UTC, swopebe requested changes
see comments

2021-06-25 13:54 UTC, swopebe commented on content/concepts/placement.md
> +
change any "as below" to:

As seen in the following examples.

2021-06-25 14:03 UTC, swopebe commented on content/concepts/placement.md
> +
Same here, change "below". Below and any other directional terms can disorient a use who relies on a screen reader.

2021-06-25 14:20 UTC, qiujian16 commented on content/concepts/placement.md
> +A slice of `PlacementDecision` will be created by placement controller in the same namespace, each with a label of `open-cluster-management.io/placemeent=placement1`. `PlacementDecision` contains the
updated

2021-06-25 14:21 UTC, qiujian16 commented on content/concepts/placement.md
> +`Placement` API is to select a set of managed clusters in one or multiple `ManagedClusterSets`, so that the user's workloads can be deployed to these clusters.
updated

2021-06-25 14:21 UTC, qiujian16 commented on content/concepts/placement.md
> +Before creating a `Placement`, you need to bind a `ManagedClusterSet` which is cluster scoped to a namespace by creating a `ManagedClusterSetBinding` in this namespace. Then you can create a `Placeme
updated

2021-06-25 14:21 UTC, qiujian16 commented on content/concepts/placement.md
> +
updated

2021-06-25 14:21 UTC, qiujian16 commented on content/concepts/placement.md
> +
updated

2021-06-26 03:37 UTC, mikeshng commented
/lgtm

2021-06-26 03:38 UTC, merged